src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/kardio/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
from . import views
from benzerdjeb import models
from benzerdjeb.views import (ListPatients, CreatePatient, DetailPatient, UpdatePatient, ListAdmissions, CurrentAdmissions, DetailAdmission, CreateAdmission, UpdateAdmission, ListBiologys, CreateBiology,  UpdateBiology, DetailBiology, admission_pdf, ListVisites, CreateVisite, DetailVisite, PatientSearchListView )
from intervention import models
from intervention.views import (ListCoronarographies, CreateCoronarographie, UpdateCoronarographie, DetailCoronarographie, UpdateCoronarographie, ListStimulations, DetailStimulation, CreateStimulation, UpdateStimulation
                                , entry_as_pdf, stimulation_pdf)

urlpatterns = [
    url(r'^accueil$', views.HomePage.as_view(), name='accueil'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url('^markdown/', include( 'django_markdown.urls')),
    #url(r'^admission/', include(admission.urls, namespace='admissions'))
    url(r'^patient/(?P<pk>\d+)/edit/$', UpdatePatient.as_view(), name='update_patient'),
    url(r'^patient/(?P<pk>\d+)/$', DetailPatient.as_view(), name='detail_patient'),
#    url(r'^delete/(?P<pk>\d+)/$', DeletePatient.as_view(), name='delete_note'),
    url(r'^patients/$', ListPatients.as_view(), name='list_patients'),
    url(r'^patient/new/$', CreatePatient.as_view(), name='create_patient'),

    url(r'^admissions/$', ListAdmissions.as_view(), name='list_admissions'),
    url(r'^nouvelle_admission/$', CreateAdmission.as_view(), name='create_admission'),
    url(r'^admission/(?P<pk>\d+)/edit/$', UpdateAdmission.as_view(), name='update_admission'),
    url(r'^admission/(?P<pk>\d+)/$', DetailAdmission.as_view(), name='detail_admission'),
#    url(r'^bilans/$', ListBiologys.as_view(), name='list_biologys'),
    url(r'^bilan/new/$', CreateBiology.as_view(), name='create_biology'),
    url(r'^bilan/(?P<pk>\d+)/edit/$', UpdateBiology.as_view(), name='edit_biology'),
#    url(r'^bilan/(?P<pk>\d+)/delete/$', DeleteBiology.as_view(), name='delete_biology'),
    url(r'^bilan/(?P<pk>\d+)/$', DetailBiology.as_view(), name='detail_biology'),
    url(r'^bilans/$', ListBiologys.as_view(), name='list_biologys'),
    url(r'^coronarographies/$', ListCoronarographies.as_view(), name='list_coronarographies'),
    url(r'^coronarographie/(?P<pk>\d+)/edit/$', UpdateCoronarographie.as_view(), name='update_coronarographie'),
    url(r'^coronarographie/(?P<pk>\d+)/$', DetailCoronarographie.as_view(), name='detail_coronarographie'),
    url(r'^coronarographie/new/$', CreateCoronarographie.as_view(), name='create_coronarographie'),

    url(r'^stimulations/$', ListStimulations.as_view(), name='list_stimulations'),
    url(r'^stimulation/(?P<pk>\d+)/edit/$', UpdateStimulation.as_view(), name='update_stimulation'),
    url(r'^stimulation/(?P<pk>\d+)/$', DetailStimulation.as_view(), name='detail_stimulation'),
    url(r'^admission/admission(?P<pk>\d+)\.pdf$', admission_pdf, name='admission_pdf' ),
    url(r'^coronarographie/coro(?P<pk>\d+)\.pdf$', entry_as_pdf, name='rapport_coro'),

    url(r'^stimulation/new/$', CreateStimulation.as_view(), name='create_stimulation'),
    url(r'stimulation/pace(?P<pk>\d+)\.pdf$', stimulation_pdf, name='stimulation_pdf'),

    url(r'^visite/new/$', CreateVisite.as_view(), name='create_visite'),
    # url(r'^visite/(?P<pk>\d+)/edit/$', UpdateVisite.as_view(), name='edit_visite'),
#    url(r'^bilan/(?P<pk>\d+)/delete/$', DeleteBiology.as_view(), name='delete_biology'),
    url(r'^visite/(?P<pk>\d+)/$', DetailVisite.as_view(), name='detail_visite'),
    url(r'^visites/$', ListVisites.as_view(), name='list_visites'),
    url(r'^results/$', PatientSearchListView.as_view(), name='search'),

    url(r'^$', CurrentAdmissions.as_view(), name='home'),
  #   url(r'^admission_bis/(?P<pk>\d+)\.pdf$', secondview, name='admission_pdf' )
]
 #User-uploaded files like profile pics need to be served in development

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/intervention/forms.py
# modelform pour me faciliter la vie
from django.forms import ModelForm
from intervention.models import Coronarographie, Stimulation

class CoronarographieForm(ModelForm):

    class Meta:
        model = Coronarographie
        fields = '__all__'
form1 = CoronarographieForm

class StimulationForm(ModelForm):

    class Meta:
        model = Stimulation
        fields = '__all__'
form2 = StimulationForm

src/intervention/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from intervention.models import Coronarographie, Stimulation
from benzerdjeb.models import Patient
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView
# from intervention.forms import StimulationForm, CoronarographieForm
from django.http import HttpResponse
from django.template import Context
from django.template.loader import get_template
from braces.views import LoginRequiredMixin, GroupRequiredMixin
from subprocess import Popen, PIPE
import tempfile
import os

# Create your views here.


class ListCoronarographies(LoginRequiredMixin, ListView):
    model = Coronarographie
    context_object_name = 'list_coronarographies'

class DetailCoronarographie(LoginRequiredMixin, DetailView):
    model = Coronarographie
    context_object_name = 'coronarographie'

class CreateCoronarographie(GroupRequiredMixin, CreateView):
    model = Coronarographie
    fields = '__all__'
    group_required = u'Cardiologues'
 #   success_url = reverse_lazy('list_coronarographies')
 #   success_url = reverse_lazy('coronarographie', pk = 'pk')
    success_url = reverse_lazy('list_coronarographies')

class UpdateCoronarographie(GroupRequiredMixin, UpdateView):
    model = Coronarographie
    fields = '__all__'
    group_required = u'Cardiologues'
    success_url = reverse_lazy('list_coronarographies')

class ListStimulations(LoginRequiredMixin, ListView):
    model = Stimulation
    context_object_name = 'list_stimulations'

class DetailStimulation(LoginRequiredMixin, DetailView):
    model = Stimulation
    context_object_name = 'stimulation'

class CreateStimulation(GroupRequiredMixin, CreateView):
    model = Stimulation
    fields = '__all__'
    group_required = u'Cardiologues'
    success_url = reverse_lazy('list_stimulations')
   # success_url = 'list_stimulations'


class UpdateStimulation(GroupRequiredMixin, UpdateView):
    model = Stimulation
    fields = '__all__'
    group_required = u'Cardiologues'
    success_url = reverse_lazy('list_stimulations')

def entry_as_pdf(request, pk):
    entry = Coronarographie.objects.get(pk=pk)
    context = Context({ 'coronarographie': entry })
    template = get_template('intervention/coro.tex')
    rendered_tpl = template.render(context, request).encode('utf-8')
    # Python3 only. For python2 check out the docs!
    with tempfile.TemporaryDirectory() as tempdir:
        # Create subprocess, supress output with PIPE and
        # run latex twice to generate the TOC properly.
        # Finally read the generated pdf.
        for i in range(2):
            process = Popen(
                ['xelatex', '-output-directory', tempdir],
                stdin=PIPE,
                stdout=PIPE,
            )
            process.communicate(rendered_tpl)
        with open(os.path.join(tempdir, 'texput.pdf'), 'rb') as f:
            pdf = f.read()
    r = HttpResponse(content_type='application/pdf')
    # r['Content-Disposition'] = 'attachment; filename=texput.pdf'
    r.write(pdf)
    return r

def stimulation_pdf(request, pk):
    entry = Stimulation.objects.get(pk=pk)
    # source = Patient.objects.get(pk=pk)
    # context = Context({ 'stimulation': entry, 'patient': source })

    context = Context({ 'stimulation': entry })
    template = get_template('intervention/pace.tex')
    rendered_tpl = template.render(context, request).encode('utf-8')
    # Python3 only. For python2 check out the docs!
    with tempfile.TemporaryDirectory() as tempdir:
        # Create subprocess, supress output with PIPE and
        # run latex twice to generate the TOC properly.
        # Finally read the generated pdf.
        for i in range(2):
            process = Popen(
                ['xelatex', '-output-directory', tempdir],
                stdin=PIPE,
                stdout=PIPE,
            )
            process.communicate(rendered_tpl)
        with open(os.path.join(tempdir, 'texput.pdf'), 'rb') as f:
            pdf = f.read()
    r = HttpResponse(content_type='application/pdf')
    # r['Content-Disposition'] = 'attachment; filename=texput.pdf'
    r.write(pdf)
    return r

src/intervention/templates/intervention/coronarographie_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %}{{ block.super }}{% if coronarographie.conclusion %}Coronarographie{% endif %}{% if coronarographie.procedure %} - Angioplastie{% endif %}{% endblock %}

{% block container %}
<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ coronarographie.patient }}</h1>

   <!-- à remplacer par edit admission  {% if editable %}
  <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Edit Profile</a>
      {% endif %} -->
    </div>
    <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'logo.png' 140x140 crop %}">
    </div>
  </div>
</div>


<div class="container profile-body">
  <div class="row">
    <div class="col-sm-4">
      <ul class="list-group">

        <li class="list-group-item text-left"><strong>Indication: {% for indication in coronarographie.indication.all %} {{ indication }} {% endfor %}</li>

        <li class="list-group-item text-left"><strong> Date de l'intervention: {{ coronarographie.intervention_date }}</strong></li>

	  <!--  <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span> -->
	    <li class="list-group-item text-left"><strong> Médecin opérateur: {{ coronarographie.operateur }}</li>
      {% if coronarographie.aide %}<li class="list-group-item text-left">Aide: <strong>{{ coronarographie.aide }}</strong></li>{% endif %}
      <li class="list-group-item text-muted">Materiel</li>
      <li class="list-group-item text-left"><strong>Guides: {% for guide in coronarographie.guide.all %} {{ guide }} {% endfor %}</li>
      <li class="list-group-item text-left"><strong>Sondes: {% for sonde in coronarographie.sonde.all %} {{ sonde }} {% endfor %}</li>
      <li class="list-group-item text-left"><strong>Ballons: {% for ballon in coronarographie.ballon.all %} {{ indication }} {% endfor %}</li>
      <li class="list-group-item text-left"><strong>Stents: {% for stent in coronarographie.stent.all %} {{ stent }} {% endfor %}</li>
      <li class="list-group-item text-left"><strong>Produit de contrast: {{ coronarographie.iode }} cc</strong></li>
	<!--    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="This email address is not verified"></span>-->

<li class="list-group-item text-left"><a href="{% url 'rapport_coro' pk=coronarographie.pk %}" >Imprimer rapport <span class ="glyphicon glyphicon-print"></span></a></li>
 <li class="list-group-item text-left"><a href="{% url 'update_coronarographie' pk=coronarographie.pk %}" >Modifier rapport <span class ="glyphicon glyphicon-pencil"></span></a></li>
  

      <!--  <li class="list-group-item text-left"><strong>Last seen</strong> {{ show_user.last_login }}</li>-->
      </ul>



    </div>



    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-heading">{% if coronarographie.conclusion %}Coronarographie {% endif %}-{%if coronarographie.procedure %} Angioplastie{% endif %}</div>
        <div class="panel-body">
	   {% if coronarographie.conclusion %}<h2> Réseau coronaire </h2>{% endif %}


         <div><h3>Tronc commun gauche (TCG)</h3>
           <p>{{  coronarographie.tcg }}</p>

         </div>

      {% if coronarographie.bissectrice%}   <div><h4>Bissectrice</h4>
           <p>{{  coronarographie.bissectrice }}</p>

         </div> {% endif %}
         <div><h4>Inter ventriculaire antérieure (IVA)</h4>
           <p>{{  coronarographie.iva }}</p>

         </div>
         <div><h4>Circonflexe (Cx)</h4>
           <p>{{  coronarographie.circonflexe }}</p>

         </div>
         <div><h4>Coronaire droite (CD)</h4>
           <p>{{  coronarographie.coronaire_dte }}</p>
           <p>Dominance: {% if coronarographie.dominance == True %}droite{% elif coronarographie.dominance == False %}gauche{% else %}co-dominance {% endif %}</p>

         </div>




            <div><h2>Conclusion</h2>
              <p>{{ coronarographie.conclusion }}</p>
            </div>

            <div><h2>Décision du {{ coronarographie.staff_date }}</h2>


     <p>{{ coronarographie.decision }}</p>

            </div>


            <div><h2>Angioplastie</h2>

              <p> {{ coronarographie.procedure }}
              </p>
              <hr>

              <h4>Complications</h4>
             <p>{% for complication in coronarographie.complication.all %} {{ complication }} {% endfor %}</p>
             <h3>Dispositions complémentaires</h3>
             <p>{{ coronarographie.dispositions }}</p>

            </div>

     </div>
    </div>

  </div>
</div>

</div>

{% endblock  %}

src/intervention/templates/intervention/coronarographie_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block title %}{{ block.super }}Nouveau patient{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block container %}

  <div class="row">
    <div class="col-md-6">
      <h1>Coronarographie | Angioplastie</h1>
      <hr/>
      <div class="well">
        <form method="POST" action="."> {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="valider" class="btn btn-success btn-lg btn-block" >
      </form>
      </div>
    </div>
  </div>
{% endblock %}

src/intervention/templates/intervention/coronarographie_list.html
        {% extends "base.html" %}
        {% load staticfiles %}
        {% load thumbnail %}


        {% block title %}{{ block.super }}Procédures de pacing{% endblock %}




        {% block container %}

<div class="container" >

    <div class="container profile-head">
        <div class="row">
            <div class="col-sm-10">
                <h1><huge>CORONAROGRAPHIES</huge></h1>
                <!--      {% if editable %}
                     <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Edit Profile</a>
                     {% endif %} -->
            </div>
            <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'logo.png' 140x140 crop %}">
            </div>
        </div>
    </div>



<table class="table table-compact table-striped table-hover">
                <tr>
                  <th>Patient</th>
                  <th>Intervention</th>
                  <th>Date</th>
                  <th>Medecin</th>
                  <th>indication </th>

                  <th>conclusion</th>
                  <th>dispositions</th>
                  <th>PDF</th>
                  <th>Édier</th>
                </tr>
            
                {% for coronarographie in list_coronarographies %}
                <tr>
                    <td><a href="{% url 'detail_coronarographie' pk=coronarographie.pk %}">{{ coronarographie.patient }}</a></td>

                    <td> {% if coronarographie.conclusion  %} Coronarographie {% endif %} {% if coronarographie.procedure %}Angioplastie{% endif %}</td>

                    <td>{{coronarographie.intervention_date }}</td>
                    <td>{{ coronarographie.operateur }}</td>
                    <td> {% for indication in coronarographie.indication.all  %}{{ indication }} {% endfor %}</td>
                        
                    <td>{{ coronarographie.conclusion }}</td>
                    <td>{{ coronarographie.dispositions }}</td>

                    <td><a href="{% url 'rapport_coro' pk=coronarographie.pk %}" <span class="glyphicon glyphicon-print" aria-hidden="true"></span></td>
<td><a href="{% url 'update_coronarographie' pk=coronarographie.pk %}"><span class ="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>

                </tr>
                {% endfor %}
</table>
<a class="btn btn-default " href="{% url 'create_coronarographie' %}" >
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ajouter coro
</a>
 </div>
{% endblock container %}

{% block scripts %}

        <script src="{% static 'site/js/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'site/js/site.js' %}"></script>
        {% endblock scripts %}

  

src/intervention/templates/intervention/stimulation_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %}{{ block.super }}Pacing{% endblock %}

{% block container %}
<div class="container profile-head">
    <div class="row">
        <div class="col-sm-10">
            <h1>{{ stimulation.patient }} <small>le {{ stimulation.intervention_date }}</small></h1>
            

            <!-- à remplacer par edit admission  {% if editable %}
                 <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Edit Profile</a>
                 {% endif %} -->
        </div>
        <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'logo.png' 140x140 crop %}">
        </div>
    </div>
</div>

<div><h3> Protocole opératoire de {% if stimulation.epuisement == False %}primo-implantation {% else %}changement de boîtier{% endif %} de Pace-maker {% if stimulation.type_stimulation == 'DDD' %}double chambre {% else %}mono chambre {% endif %} type {{ stimulation.type_stimulation }}</h2>
    <hr>

    <div class="container profile-body">
        <div class="row">
            <div class="col-sm-4">
                <ul class="list-group">


                    <li class="list-group-item text-left"><strong> Date de l'intervention: {{ stimulation.intervention_date }}</strong></li>

	                  <!--  <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span> -->
	                  <li class="list-group-item text-left"><strong> Médecin opérateur: {{ stimulation.operateur }}</li>
                        {% if stimulation.aide %}<li class="list-group-item text-left">Aide: <strong>{{ stimulation.aide }}</strong></li>{% endif %}
                        <li class="list-group-item text-left"><strong>Indication: {% for indication in stimulation.indication.all %} {{ indication }} {% endfor %}</li>


                            <li class="list-group-item text-left"><strong>Pace: {{ stimulation.pacemaker }} </li>
                                <li class="list-group-item text-left"><strong>Type de stimulation: {{ stimulation.type_stimulation }} </li>
                                    <li class="list-group-item text-left"><strong>Durée de la procédure: {{ stimulation.duree }} </li>

                                        
                                        <li class="list-group-item text-left"><a href="{% url 'stimulation_pdf' pk=stimulation.pk %}" >Imprimer rapport <span class ="glyphicon glyphicon-print"></span></a></li>


                                        <!--  <li class="list-group-item text-left"><strong>Last seen</strong> {{ show_user.last_login }}</li>-->
                </ul>



            </div>



            <div class="col-sm-8">
                <div class="panel panel-default">
                    <div class="panel-heading"> </div>
                    <div class="panel-body">

                        <H2>Procédure</h2>
                        
                        <p> {{ stimulation.procedure }}
                        </p>
                        <hr>



                        <h3>Complications</h3>
                        <p>{% for complication in stimulation.complication.all %} {{ complication }} {% endfor %}</p>

                        <h3>Dispositions complémentaires</h3>
                        <p>{{ stimulation.dispositions }}</p>

                    </div>

                </div>
            </div>
            
        </div>
    </div>
    
</div>

{% endblock  %}

src/intervention/templates/intervention/stimulation_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block title %}{{ block.super }}Nouveau patient{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block container %}

  <div class="row">
    <div class="col-md-6">
      <h1>Stimulation</h1>
      <hr/>
      <div class="well">
        <form method="POST" action="."> {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="valider" class="btn btn-success btn-lg btn-block" >
      </form>
      </div>
    </div>
  </div>
{% endblock %}

src/intervention/templates/intervention/stimulation_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}


{% block title %}{{ block.super }}Procédures de pacing{% endblock %}




{% block container %}

<div class="container">

  <div class="container profile-head">
        <div class="row">
            <div class="col-sm-10">
                <h1><huge>PACING</huge></h1>
                <!--      {% if editable %}
                     <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Edit Profile</a>
                     {% endif %} -->
            </div>
            <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'logo.png' 140x140 crop %}">
            </div>
        </div>
    </div>



    <table class="table table-compact table-striped table-hover">
        <tr>
            <th>Patient</th>
            <th>Date</th>
            <th>Medecin</th>
            <th>indication </th>
            
            <th>Type</th>
            <th>PDF</th>
            <th>Éditer</th> 
        </tr>
        
        {% for stimulation in list_stimulations %}
        <tr>
            <td><a href="{% url 'detail_stimulation' pk=stimulation.pk %}">{{ stimulation.patient }}</a></td>
            
            <td>{{ stimulation.intervention_date }}</td>
            <td>{{ stimulation.operateur }}</td>
            <td> {% for indication in stimulation.indication.all  %}{{ indication }} {% endfor %}</td>
            
            <td>{{ stimulation.stimulation_type }}</td>
             <td><a href="{% url 'stimulation_pdf' pk=stimulation.pk %}"><span class ="glyphicon glyphicon-print" aria-hidden="true"></span></td>
           <td><a href="{% url 'update_stimulation' pk=stimulation.pk %}"><span class ="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
            
        </tr>
        {% endfor %}
    </table>
    <a class="btn btn-default " href="{% url 'create_stimulation' %}" >
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ajouter stim
    </a>
</div>



{% endblock container %}

{% block scripts %}

<script src="{% static 'site/js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}