src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/kardio/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
from . import views
from benzerdjeb import models
from benzerdjeb.views import (ListPatients, CreatePatient, DetailPatient, UpdatePatient, ListAdmissions, CurrentAdmissions, DetailAdmission, CreateAdmission, UpdateAdmission, ListBiologys, CreateBiology,  UpdateBiology, DetailBiology, admission_pdf, ListVisites, CreateVisite, DetailVisite, PatientSearchListView )
from intervention import models
from intervention.views import (ListCoronarographies, CreateCoronarographie, UpdateCoronarographie, DetailCoronarographie, UpdateCoronarographie, ListStimulations, DetailStimulation, CreateStimulation, UpdateStimulation
                                , entry_as_pdf, stimulation_pdf)

urlpatterns = [
    url(r'^accueil$', views.HomePage.as_view(), name='accueil'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url('^markdown/', include( 'django_markdown.urls')),
    #url(r'^admission/', include(admission.urls, namespace='admissions'))
    url(r'^patient/(?P<pk>\d+)/edit/$', UpdatePatient.as_view(), name='update_patient'),
    url(r'^patient/(?P<pk>\d+)/$', DetailPatient.as_view(), name='detail_patient'),
#    url(r'^delete/(?P<pk>\d+)/$', DeletePatient.as_view(), name='delete_note'),
    url(r'^patients/$', ListPatients.as_view(), name='list_patients'),
    url(r'^patient/new/$', CreatePatient.as_view(), name='create_patient'),

    url(r'^admissions/$', ListAdmissions.as_view(), name='list_admissions'),
    url(r'^nouvelle_admission/$', CreateAdmission.as_view(), name='create_admission'),
    url(r'^admission/(?P<pk>\d+)/edit/$', UpdateAdmission.as_view(), name='update_admission'),
    url(r'^admission/(?P<pk>\d+)/$', DetailAdmission.as_view(), name='detail_admission'),
#    url(r'^bilans/$', ListBiologys.as_view(), name='list_biologys'),
    url(r'^bilan/new/$', CreateBiology.as_view(), name='create_biology'),
    url(r'^bilan/(?P<pk>\d+)/edit/$', UpdateBiology.as_view(), name='edit_biology'),
#    url(r'^bilan/(?P<pk>\d+)/delete/$', DeleteBiology.as_view(), name='delete_biology'),
    url(r'^bilan/(?P<pk>\d+)/$', DetailBiology.as_view(), name='detail_biology'),
    url(r'^bilans/$', ListBiologys.as_view(), name='list_biologys'),
    url(r'^coronarographies/$', ListCoronarographies.as_view(), name='list_coronarographies'),
    url(r'^coronarographie/(?P<pk>\d+)/edit/$', UpdateCoronarographie.as_view(), name='update_coronarographie'),
    url(r'^coronarographie/(?P<pk>\d+)/$', DetailCoronarographie.as_view(), name='detail_coronarographie'),
    url(r'^coronarographie/new/$', CreateCoronarographie.as_view(), name='create_coronarographie'),

    url(r'^stimulations/$', ListStimulations.as_view(), name='list_stimulations'),
    url(r'^stimulation/(?P<pk>\d+)/edit/$', UpdateStimulation.as_view(), name='update_stimulation'),
    url(r'^stimulation/(?P<pk>\d+)/$', DetailStimulation.as_view(), name='detail_stimulation'),
    url(r'^admission/admission(?P<pk>\d+)\.pdf$', admission_pdf, name='admission_pdf' ),
    url(r'^coronarographie/coro(?P<pk>\d+)\.pdf$', entry_as_pdf, name='rapport_coro'),

    url(r'^stimulation/new/$', CreateStimulation.as_view(), name='create_stimulation'),
    url(r'stimulation/pace(?P<pk>\d+)\.pdf$', stimulation_pdf, name='stimulation_pdf'),

    url(r'^visite/new/$', CreateVisite.as_view(), name='create_visite'),
    # url(r'^visite/(?P<pk>\d+)/edit/$', UpdateVisite.as_view(), name='edit_visite'),
#    url(r'^bilan/(?P<pk>\d+)/delete/$', DeleteBiology.as_view(), name='delete_biology'),
    url(r'^visite/(?P<pk>\d+)/$', DetailVisite.as_view(), name='detail_visite'),
    url(r'^visites/$', ListVisites.as_view(), name='list_visites'),
    url(r'^results/$', PatientSearchListView.as_view(), name='search'),

    url(r'^$', CurrentAdmissions.as_view(), name='home'),
  #   url(r'^admission_bis/(?P<pk>\d+)\.pdf$', secondview, name='admission_pdf' )
]
 #User-uploaded files like profile pics need to be served in development

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/benzerdjeb/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.conf import settings
from django.core.urlresolvers import reverse

class   Wilaya(models.Model):
                wilaya = models.CharField(max_length=25)

                def __str__(self):
                    return(self.wilaya)


class   Motif(models.Model):
                motif = models.CharField(verbose_name="motif d'admission", max_length=25)

                def __str__(self):
                    return(self.motif)

class   Tag(models.Model):
                tag = models.CharField(max_length=50, blank=True)

                def __str__(self):
                    return(self.tag)


class   Patient(models.Model):
                name = models.CharField(verbose_name="nom et prénoms", max_length=50)
                birth = models.DateField(verbose_name="date de naissance")
                GENDER_CHOICES = (
                     ('M', 'Masculin'),
                     ('F', 'Féminin'),
                )
                gender = models.CharField(verbose_name="sexe", max_length=1, choices=GENDER_CHOICES)
                ardress = models.ForeignKey(Wilaya)
                phone = models.CharField("Téléphone", max_length=10, default='0550123456')
                assured = models.BooleanField(verbose_name="assuré social", default=True)
                correspondant = models.CharField("Médecin correspondant", max_length=255, blank=True)
                first_admission = models.DateField("première admission", default=timezone.now)
                hypertension = models.BooleanField("hypertendu(e)", default=True)
                diabete = models.BooleanField("diabétique", default=True)
                dyslipidemia = models.BooleanField("dyslipidémie", default=True)
                smoker = models.BooleanField("tabagique", default=False)
                weight = models.PositiveSmallIntegerField(verbose_name="poids", blank=True)
                lenght = models.DecimalField(max_digits=3, decimal_places=2, default=1.70)
                #bmi = weight/lenght*lenght
                obesity = models.BooleanField("obèse", default=True)
                sedentarity = models.BooleanField("sédentarité", default=True)
                heredity = models.BooleanField("hérédité coronarienne", default=False)
                history = models.TextField("antécedents")
                allergy = models.CharField("allergie connue", max_length=50, blank=True)
                tags = models.ManyToManyField(Tag, default="cardio")

                class Meta:
                    ordering = ['name']

                def get_absolute_url(self):
                    return reverse('detail_patient', kwargs={'pk': self.pk})

                def __str__(self):
                    return(self.name)





class   Admission(models.Model):

# données générales et symptomatologie

                patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
                admission_date = models.DateField("date d'admission")
                medecin = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True)
                emergency = models.BooleanField("urgence", default=False)
                motif_admission = models.ManyToManyField(Motif)
                fever = models.BooleanField("fièvre", default=False)
                dyspnea_nyha = models.PositiveSmallIntegerField("stade NYHA", default='1')
                angina_scc = models.PositiveSmallIntegerField("stade d'angor", default='1')
                syncope = models.BooleanField("Syncope", default=False)
                histoire = models.CharField("Histoire de la maladie", max_length=255 ,null=True, blank=True)

# examen clinique

                systolic_bp = models.PositiveSmallIntegerField(blank=True)
                diastolic_bp = models.PositiveSmallIntegerField(blank=True)
                heart_rate = models.PositiveSmallIntegerField(blank=True)
                auscultation = models.CharField(max_length=50, blank=True)
                ivg = models.BooleanField(default=False)
                ivd = models.BooleanField(default=False)
                pulse = models.CharField(max_length=50, blank=True)
                telethorax = models.CharField(max_length=50, blank=True)

                # ECG

                RYTHM_CHOICES = (
                    ('S', 'Sinusal'),
                    ('F', 'Atrial Fibrillation'),
                    ('R', 'Atrial Flutter'),
                    ('P', 'Pace Maker'),
                    ('T', 'TV')
                )
                rythm = models.CharField(max_length=1, choices=RYTHM_CHOICES)
                freq = models.PositiveSmallIntegerField(default='70')
                BLOCK_CHOICES = (
                    ('D', 'BBD'),
                    ('G', 'BBG'),
                    ('N', 'Null')
                    )
                bundle_block = models.CharField(max_length=1, choices=BLOCK_CHOICES, blank=True)

                hypertrophy = models.NullBooleanField(default=False)
                TERRITORY = (
                    ('N', 'Null'),
                    ('S', 'Septal'),
                    ('A', 'Anterior'),
                    ('L', 'Lateral'),
                    ('P', 'Posterior'),
                )
                necrosis = models.CharField(max_length=1, choices=TERRITORY)
                ischaemia = models.CharField(max_length=1, choices=TERRITORY)
                lesion = models.CharField(max_length=1, choices=TERRITORY)
                t_inversion = models.CharField(max_length=1, choices=TERRITORY)
                corrected_qt = models.IntegerField(default=400)
#echocoeur
                echocoeur = models.TextField("échocardiographie", null=True, blank=True)
                date_echo = models.DateField("Date de l'écho", default=timezone.now)
                eto = models.TextField("échocardiographie trans-oesophagienne", null=True, blank=True)

                fevg = models.PositiveSmallIntegerField("FeVG", blank=True, null=True)

#evolution

                resume = models.TextField("résumé clinique", null=True)
                evolution = models.CharField("évolution de la maladie", max_length=255, blank = True, null=True)

# ordonnance de sortie

                beta_blocker = models.BooleanField("béta bloquant", default=True)
                ace = models.BooleanField("inhibiteur de l'enzyme de conversion", default=True)
                plavix = models.BooleanField(default=True)
                aspegic = models.BooleanField(default=True)
                statin = models.BooleanField("statine", default=True)
                heparin = models.BooleanField("héparines", default=True)
                furosemid = models.BooleanField("furosemide", default=True)
                aldactone = models.BooleanField(default=True)
                nitrine = models.BooleanField("dérivés nitrés", default=False)
                insulin = models.BooleanField("insuline", default=False)
                oral_anti_diabetic = models.BooleanField("anti diabétiques oraux", default=True)
                avk = models.BooleanField("AVK", default=False)
# discharge
                date_sortie = models.DateField(blank=True, null=True)
                dispositions = models.CharField("dispositions complémentaires", max_length=255, blank=True)
# mesurer la durée d'hospitalisation à la django!

                duration = models.DurationField("durée de l'hospitalisation", blank=True)

                def save(self, *args, **kwargs):
                                if self.date_sortie:
                                                self.duration = self.date_sortie - self.admission_date
                                else:
                                                self.duration = datetime.now().date() - self.admission_date

                                super(Admission, self).save(*args, **kwargs)

#                EVOLUTION_CHOICES = (
#                    ('F', 'Favorable'),
#                    ('S', 'Stable'),
#                    ('G', 'Aggravation'),
#                    ('D', 'Décès'),
#                )
#                evolution_items = models.CharField(max_length=1, choices=EVOLUTION_CHOICES)
                treatement = models.CharField("ordonnance de sortie", max_length=100)
                sortant = models.BooleanField(default=False)

                def __str__(self):

                    return '%s %s' % (self.patient, self.admission_date)
                def get_absolute_url(self):
                    return reverse('detail_admission', kwargs={'pk': self.pk})

class Biology(models.Model):
                patient = models.ForeignKey(Patient)
                prelevement = models.DateField(blank=True, default = timezone.now)
# Biologie
                glycemia = models.DecimalField(max_digits=4, decimal_places=2, default=1.00)
                creatinin = models.DecimalField(max_digits=5, decimal_places=2, default=9)
                mdrd = models.PositiveSmallIntegerField()
                troponin = models.PositiveSmallIntegerField("taux de troponines/ normale", default=1)
                cholesterol = models.DecimalField(max_digits=3, decimal_places=2, default=1.00)
                triglyceride = models.DecimalField(max_digits=3, decimal_places=2, default=1.00)
                hdl = models.DecimalField(max_digits=3, decimal_places=2, default=1.00)
                ldl = models.DecimalField(max_digits=3, decimal_places=2, default=1.00)

                def __str__(self):
                    return '%s %s' % (self.patient, self.prelevement)
                def get_absolute_url(self):
                    return reverse('detail_biology', kwargs={'pk': self.pk})


class   Visite(models.Model):

# données générales et symptomatologie

                patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
                visite_date = models.DateField("date de la visite", default=timezone.now)

src/templates/_brandname.html
CARDIO | EH Dr.Benzerdjeb

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>
<!--<li {% if active_link == "patients" %}class="active"{% endif %}<a href="{ url 'patient_list'}">Patients</a></li>-->

src/templates/base.html
<!DOCTYPE html>
<html lang="fr">
    {% load staticfiles %}
    {% load thumbnail %}
    
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{% block description %}{% endblock description %}">
        <meta name="author" content="Dr.Yahyaoui Mohamed Kaddour">
        <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">
        
        <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom styles for this site -->
        {% block styles %}
    
        <link href="{% static 'site/css/main.min.css' %}" rel="stylesheet"> 
        <!-- <link href="{% static 'site/css/custom.css' %}" rel="stylesheet">  -->
        {% endblock styles %}
        
        <!-- Custom tags for the head tag -->
        {% block extrahead %}{% endblock extrahead %}

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    </head>

    <body>

        {% block navbar %}
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">

                <div class="navbar-header">

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="{% url 'home' %}">


                        {% block navbar-brand %}
                        <!--- <img src="{% static 'site/img/logo.png' %}" alt="logo"> --->
                        {% include "_brandname.html" %}
                        {% endblock %}
                    </a>

                </div>
                {% block navbar-menu %}



                <div class="collapse navbar-collapse" id="mainNavBar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'home' %}"><span class ="glyphicon glyphicon-home"></span> Home</a></li>
                        
                        <!-- drop down menu -->
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class ="glyphicon glyphicon-bed"></span> Service <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'create_patient' %}">Ajouter patient</a></li>
                                <li><a href="{% url 'create_admission' %}">Ajouter admission</a></li>
                                <li><a href="{% url 'create_biology' %}">Ajouter bilan</a></li>
                                
                                <li><a href="{% url 'create_visite' %}">Ajouter visite</a></li>
                                <!--<li><a href="#">Friends</a></li>
                                     <li><a href="#">Photos</a></li>
                                     <li><a href="#">Settings</a></li> --->
                            </ul>
                        </li>
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class ="glyphicon glyphicon-heart"></span> Bloc<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'create_coronarographie' %}">Ajouter coronarographie</a></li>
                                <li><a href="{% url 'create_stimulation' %}">Ajouter stimulation</a></li>
                                

                                <!--<li><a href="#">Friends</a></li>
                                     <li><a href="#">Photos</a></li>
                                     <li><a href="#">Settings</a></li> --->
                            </ul>
                        </li>
                    </ul>

                    <!--right align -->
                    <ul class="nav navbar-nav navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            {% block navbar-right %}
                            {% if user.is_authenticated %}
                            {% if user.is_staff %}
                            <li><a href="{% url 'admin:index' %}">Admin</a></li>
                            {% endif %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
    			                          <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 20x20 crop %}" alt="" />
    			                          {{ user.get_full_name|truncatechars:20 }}
    			                          <span class="caret"></span>
    		                        </a>
                                
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                                    <!---  <li><a href="{% url 'create_patient' %}">New patient</a></li>
                                         <li><a href="{% url 'create_admission' %}">New admission</a></li> --->
                                </ul>
                                
                                {% endif %}
                                {% endblock %}
                        </ul>
                    </ul>
                    
                </div>






            </div>
        </nav>
        {% endblock %}
        {% endblock %}

        {% block nav-pills %}

        <div class ="col-lg-12"> 
            <ul class="nav nav-pills" >
                <li class="active"><a href="{% url 'home'%}"><span class ="glyphicon glyphicon-home"></span> Home</a></li>
                
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        <span class ="glyphicon glyphicon-bed"></span> Service <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li ><a href="{% url 'list_patients' %}">Patients</a></li>
                        <li ><a href="{% url 'list_admissions' %}">Admissions</a></li>
                        
                        <li ><a href="{% url 'list_visites' %}">Visites</a></li>
                    </ul>
                    
                    
                    <li role="presentation" class="dropdown" >
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class ="glyphicon glyphicon-heart"></span> Bloc <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li ><a href="{% url 'list_coronarographies' %}">coronarographies</a></li>
                            <li ><a href="{% url 'list_stimulations' %}">Pacing</a></li>
                            
                    </li>

                        </ul>


                        <li ><a href="{% url 'list_biologys' %}"><span class ="glyphicon glyphicon-tint"></span> Bilans</a></li>
                        
            </ul>
            
                    </ul>
        </div> 
        
        <div class="col-sm-3 col-md-3 pull-right">
            <form class="navbar-form" role="search" action="{% url 'search' %}" method="get" accept-charset="utf-8"> 
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="q" id="searchform">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
        <!-- <form class="navbar-form" id="searchform" role="search" action="{% url 'search' %}" method="get" accept-charset="utf-8"> -->
        <!-- <button class="searchbutton" type="submit"> -->
        <!-- <i class="glyphicon glyphicon-search"></i> -->
        <!-- </button> -->
        <!-- <input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search"> -->
        <!-- </form> -->
        {% endblock nav-pills %}
        
        {% block messages %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        {% endblock %}

        {% block splash %}
        {% endblock splash %}



        <hr>

        {% block container %}
        <div class="container">


<form id="searchform" value="{{ query }}" action="{% url 'search' %}" method="get" accept-charset="utf-8">
      <button class="searchbutton" type="submit">
        <i class="glyphicon glyphicon-search"></i>
      </button>
      <input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
                            </form>



            <div class="starter-template">
                <h1>Cardiologie</h1>
                <p class="lead">Bienvenue dans le service cardiologie de l'EH Dr.Benzerdjeb.<br> Vous êtes dans l'application kardio, développée par et pour les memebres du service afin d'automatiser la saisie des dossiers médicaux.</p>
            </div>
            
        </div><!-- /.container -->




        {% endblock container %}

    <!-- Site footer -->
        {% block footer %}
      <!-- Some social button for contact will do -->
      <hr> 
        <div class="container">
            <div class="footer">
                <div class="row">
                    <div class="col-lg-6">
                        <p>&copy; Cardiologie EH Dr.Benzerdjeb {% now 'Y' %}</p>
                    </div>
                </div>
            </div>
        </div>
                    {% endblock %}
                    
                    
                    {% block scripts %}
                    <!-- Bootstrap core JavaScript
                         ================================================== -->
                    <!-- Placed at the end of the document so the pages load faster -->
                    <script src="{% static 'site/js/jquery.min.js' %}"></script>
                    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
                    <script src="{% static 'site/js/main.min.js' %}"></script>
                    
                    {% endblock scripts %}
    </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
    {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>
          <p>l'application du service cardiologie</p>
<!--	  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up for Free!</a> -->
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">

<div class="col-md-4">
  <div class="well">

      <h2>Présentation</h2>
      <p>Basée sur le framwork django, cette application vise à automatiser la saisie des données médicales et à gérer les dossiers, ainsi que produire des rapports de qualité. </p>
      <p><a class="btn btn-primary" href="#" role="button"> vue d'ensemble</a></p>
    </div>
  </div>
<div class="col-md-4">
  <div class="well">

      <h2>Patients</h2>
      <p>Liste des patients vus dans notre département, historique médical ainsi que  leurs principales caractéristiques démographiques </p>
      <p><a class="btn btn-primary" href="{% url 'list_patients' %}" role="button">patients</a></p>
    </div>
  </div>
<div class="col-md-4">
  <div class="well">

      <h2>Admission</h2>
      <p>Liste des hospitalisations, triées par ordre chronologique.
        Les rapports sont genérés automatiquement à partir des formulaires</p>
      <p><a class="btn btn-primary" href="{% url 'list_admissions' %}" role="button">admissions</a></p>
    </div>
  </div>
</div>

{% endblock container %}

<!--    {% block scripts %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'site/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site/js/site.js' %}"></script>

    {% endblock scripts %}
    -->
    </body>
    </html>